In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [16]:
np.zeros((4,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones(4)

array([1., 1., 1., 1.])

In [18]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
np.linspace(0,11,10)

array([ 0.        ,  1.22222222,  2.44444444,  3.66666667,  4.88888889,
        6.11111111,  7.33333333,  8.55555556,  9.77777778, 11.        ])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.random.rand(5)

array([0.04714993, 0.2847347 , 0.96732083, 0.66013059, 0.85082896])

In [24]:
np.random.rand(5,5)

array([[0.06460993, 0.67799035, 0.13072796, 0.36786959, 0.14063018],
       [0.57915911, 0.76096995, 0.79644995, 0.09465933, 0.25683977],
       [0.34646467, 0.35107275, 0.96944719, 0.62410374, 0.26017151],
       [0.38336972, 0.71419226, 0.21564252, 0.37648731, 0.72160026],
       [0.70768453, 0.94697113, 0.90607872, 0.00752377, 0.16847493]])

In [25]:
np.random.randn(2)

array([-0.29944261, -1.52200713])

In [26]:
np.random.randn(4,4)

array([[ 0.77660509,  0.68582322,  1.071075  ,  0.08262086],
       [ 0.29293757, -0.42635636, -0.38795509,  1.0741282 ],
       [-0.11252623,  0.33898308, -0.40859131,  0.67055935],
       [-1.10864113,  0.16813865, -1.02497599, -0.63715153]])

In [27]:
np.random.randint(1,100)

31

In [28]:
np.random.randint(1,100,10)

array([97,  3, 25, 32, 79, 20, 71, 56, 49, 22])

In [29]:
arr = np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr = np.random.randint(0,50,10)

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr

array([30, 45, 37, 29, 24, 21, 31, 20, 15, 20])

In [34]:
ranarr.max()

45

In [35]:
ranarr.min()

15

In [36]:
ranarr.argmax()

1

In [37]:
ranarr.argmin()

8

In [38]:
arr.shape

(25,)

In [41]:
arr = arr.reshape(5,5)

In [42]:
arr.shape

(5, 5)

In [44]:
arr.dtype

dtype('int64')

In [45]:
arr = np.arange(0,11)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[8]

8

In [48]:
arr[3:7]

array([3, 4, 5, 6])

In [49]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [50]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [51]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [52]:
arr[0:5] = 100

In [53]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [54]:
arr = np.arange(0,11)

In [55]:
slice_of_arr = arr[0:6]

In [58]:
slice_of_arr[:] = 99

In [59]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [60]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [64]:
arr = np.arange(0,11)

In [65]:
arr_copy = arr.copy()

In [66]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr_2d = np.array([[5,10,15],[20,25,30],[30,35,40]])

In [68]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

In [69]:
arr_2d[0][0]

5

In [70]:
arr_2d[0]

array([ 5, 10, 15])

In [71]:
arr_2d[1][1]

25

In [72]:
arr_2d[2,1]

35

In [73]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [74]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])